[0m17:31:10.747784 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1115afdd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111571190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1115d7c10>]}


============================== 17:31:10.751459 | a67dfd78-1172-40f1-ba87-f0fa907db2cd ==============================
[0m17:31:10.751459 [info ] [MainThread]: Running with dbt=1.10.13
[0m17:31:10.751812 [debug] [MainThread]: running dbt with arguments {'indirect_selection': 'eager', 'introspect': 'True', 'debug': 'False', 'version_check': 'True', 'write_json': 'True', 'log_cache_events': 'False', 'warn_error': 'None', 'cache_selected_only': 'False', 'no_print': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True', 'profiles_dir': '~/.dbt', 'fail_fast': 'False', 'partial_parse': 'True', 'use_experimental_parser': 'False', 'use_colors': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'printer_width': '80', 'target_path': 'None', 'log_path': 'logs', 'static_parser': 'True', 'quiet': 'False', 'empty': 'None', 'log_format': 'default'}
[0m17:31:24.926418 [debug] [MainThread]: Starter project path: /Users/nehalkumar/Desktop/data_modelling/dbt-dl_northwind/venv/lib/python3.11/site-packages/dbt/include/starter_project
[0m17:31:24.937172 [info ] [MainThread]: 
Your new dbt project "dl_northwind" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m17:31:24.937823 [info ] [MainThread]: Setting up your profile.
[0m17:31:49.524980 [error] [MainThread]: Encountered an error:
[Errno 2] No such file or directory: '~/.dbt/profiles.yml'
[0m17:31:49.529487 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/nehalkumar/Desktop/data_modelling/dbt-dl_northwind/venv/lib/python3.11/site-packages/dbt/cli/requires.py", line 178, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nehalkumar/Desktop/data_modelling/dbt-dl_northwind/venv/lib/python3.11/site-packages/dbt/cli/requires.py", line 128, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nehalkumar/Desktop/data_modelling/dbt-dl_northwind/venv/lib/python3.11/site-packages/dbt/cli/main.py", line 483, in init
    results = task.run()
              ^^^^^^^^^^
  File "/Users/nehalkumar/Desktop/data_modelling/dbt-dl_northwind/venv/lib/python3.11/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/Users/nehalkumar/Desktop/data_modelling/dbt-dl_northwind/venv/lib/python3.11/site-packages/dbt/task/init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "/Users/nehalkumar/Desktop/data_modelling/dbt-dl_northwind/venv/lib/python3.11/site-packages/dbt/task/init.py", line 179, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "/Users/nehalkumar/Desktop/data_modelling/dbt-dl_northwind/venv/lib/python3.11/site-packages/dbt/task/init.py", line 166, in create_profile_from_profile_template
    self.write_profile(profile, profile_name)
  File "/Users/nehalkumar/Desktop/data_modelling/dbt-dl_northwind/venv/lib/python3.11/site-packages/dbt/task/init.py", line 156, in write_profile
    with open(profiles_filepath, "w") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '~/.dbt/profiles.yml'

[0m17:31:49.534528 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 38.822945, "process_in_blocks": "0", "process_kernel_time": 0.365404, "process_mem_max_rss": "358875136", "process_out_blocks": "0", "process_user_time": 1.477668}
[0m17:31:49.535797 [debug] [MainThread]: Command `dbt init` failed at 17:31:49.535666 after 38.82 seconds
[0m17:31:49.536406 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102eceb10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111038b10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111563990>]}
[0m17:31:49.536922 [debug] [MainThread]: Flushing usage events
[0m17:31:50.523175 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m20:56:54.002577 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x121314440>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x12266b890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x12266bb10>]}


============================== 20:56:54.005575 | a2c0af32-a718-4f01-b96b-e05093a3f193 ==============================
[0m20:56:54.005575 [info ] [MainThread]: Running with dbt=1.10.13
[0m20:56:54.005898 [debug] [MainThread]: running dbt with arguments {'static_parser': 'True', 'introspect': 'True', 'use_experimental_parser': 'False', 'warn_error': 'None', 'profiles_dir': '~/.dbt', 'fail_fast': 'False', 'partial_parse': 'True', 'no_print': 'None', 'log_path': 'logs', 'empty': 'None', 'log_cache_events': 'False', 'debug': 'False', 'cache_selected_only': 'False', 'send_anonymous_usage_stats': 'True', 'write_json': 'True', 'indirect_selection': 'eager', 'version_check': 'True', 'use_colors': 'True', 'invocation_command': 'dbt init', 'printer_width': '80', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'log_format': 'default', 'target_path': 'None'}
[0m20:56:54.016891 [info ] [MainThread]: Creating dbt configuration folder at ~/.dbt
[0m20:57:05.381300 [debug] [MainThread]: Starter project path: /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/dbt/include/starter_project
[0m20:57:05.392175 [info ] [MainThread]: 
Your new dbt project "Transform" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m20:57:05.392725 [info ] [MainThread]: Setting up your profile.
[0m20:57:45.746363 [error] [MainThread]: Encountered an error:
[Errno 2] No such file or directory: '~/.dbt/profiles.yml'
[0m20:57:45.759546 [error] [MainThread]: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/dbt/cli/requires.py", line 178, in wrapper
    result, success = func(*args, **kwargs)
                      ~~~~^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/dbt/cli/requires.py", line 128, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/dbt/cli/main.py", line 483, in init
    results = task.run()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/dbt/task/init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/dbt/task/init.py", line 179, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/dbt/task/init.py", line 166, in create_profile_from_profile_template
    self.write_profile(profile, profile_name)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/dbt/task/init.py", line 156, in write_profile
    with open(profiles_filepath, "w") as f:
         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '~/.dbt/profiles.yml'

[0m20:57:46.080674 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 52.11009, "process_in_blocks": "0", "process_kernel_time": 0.39045, "process_mem_max_rss": "351748096", "process_out_blocks": "0", "process_user_time": 1.49588}
[0m20:57:46.102975 [debug] [MainThread]: Command `dbt init` failed at 20:57:46.102579 after 52.13 seconds
[0m20:57:46.107025 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1688902b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x168880710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1688706b0>]}
[0m20:57:46.109163 [debug] [MainThread]: Flushing usage events
[0m20:57:47.332210 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m20:59:54.508260 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108690440>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10ba6b890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10ba6bb10>]}


============================== 20:59:54.511038 | 78edd0a0-5770-4a3c-a96b-851c1824c865 ==============================
[0m20:59:54.511038 [info ] [MainThread]: Running with dbt=1.10.13
[0m20:59:54.511365 [debug] [MainThread]: running dbt with arguments {'empty': 'None', 'use_experimental_parser': 'False', 'indirect_selection': 'eager', 'invocation_command': 'dbt debug', 'log_format': 'default', 'target_path': 'None', 'debug': 'False', 'cache_selected_only': 'False', 'no_print': 'None', 'log_path': 'logs', 'printer_width': '80', 'send_anonymous_usage_stats': 'True', 'profiles_dir': '~/.dbt', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'use_colors': 'True', 'write_json': 'True', 'log_cache_events': 'False', 'static_parser': 'True', 'quiet': 'False', 'partial_parse': 'True', 'fail_fast': 'False', 'introspect': 'True', 'version_check': 'True', 'warn_error': 'None'}
[0m20:59:54.522074 [info ] [MainThread]: dbt version: 1.10.13
[0m20:59:54.522271 [info ] [MainThread]: python version: 3.13.9
[0m20:59:54.522399 [info ] [MainThread]: python path: /Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13
[0m20:59:54.522513 [info ] [MainThread]: os info: macOS-14.4.1-arm64-arm-64bit-Mach-O
[0m20:59:54.522633 [info ] [MainThread]: Using profiles dir at ~/.dbt
[0m20:59:54.522740 [info ] [MainThread]: Using profiles.yml file at ~/.dbt/profiles.yml
[0m20:59:54.522848 [info ] [MainThread]: Using dbt_project.yml file at /Users/nehalkumar/Desktop/data_modelling/dbt-dl_northwind/dbt_project.yml
[0m20:59:54.522961 [info ] [MainThread]: Configuration:
[0m20:59:54.523064 [info ] [MainThread]:   profiles.yml file [[31mERROR not found[0m]
[0m20:59:54.523166 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m20:59:54.523268 [info ] [MainThread]: Required dependencies:
[0m20:59:54.523568 [debug] [MainThread]: Executing "git --help"
[0m20:59:54.534567 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--config-env=<name>=<envvar>] <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m20:59:54.535034 [debug] [MainThread]: STDERR: "b''"
[0m20:59:54.535255 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m20:59:54.535441 [info ] [MainThread]: Connection test skipped since no profile was found
[0m20:59:54.535816 [info ] [MainThread]: [31m2 checks failed:[0m
[0m20:59:54.535962 [info ] [MainThread]: dbt looked for a profiles.yml file in ~/.dbt/profiles.yml, but did
not find one. For more information on configuring your profile, consult the
documentation:

https://docs.getdbt.com/docs/configure-your-profile


[0m20:59:54.536089 [info ] [MainThread]: Project loading failed for the following reason:
 project path </Users/nehalkumar/Desktop/data_modelling/dbt-dl_northwind/dbt_project.yml> not found

[0m20:59:54.537739 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.06312167, "process_in_blocks": "0", "process_kernel_time": 0.113188, "process_mem_max_rss": "105431040", "process_out_blocks": "0", "process_user_time": 0.588189}
[0m20:59:54.538116 [debug] [MainThread]: Command `dbt debug` failed at 20:59:54.538048 after 0.06 seconds
[0m20:59:54.538385 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10ba8e060>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b966d50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b8f39b0>]}
[0m20:59:54.538597 [debug] [MainThread]: Flushing usage events
[0m20:59:55.742708 [debug] [MainThread]: An error was encountered while trying to flush usage events
